### ISSUE TITLE
Clarification: may harm broker if many queues

### ISSUE THREAD

**Issue by SkylerLutz** [solacecommunity/solace-prometheus-exporter#32]
Hi!

QueueStats | yes | yes | may harm broker if many queues | show queue itemFilter message-vpn vpnFilter rates count 100 (paged) | software, appliance
-- | -- | -- | -- | -- | --

What does "may harm broker if many queues" mean?
How "many"?
What's the "harm"?
Thanks!
Skyler

**Comment by GreenRover** [comment]
Hi Skyler,

aggregate those statistics takes time and cpu from broker.
So with allot of queues you might have to add an extra cpu core just for generating metrics.
I have seen higher latency in message transmission with more than 1000queues.
I would advise not to use this feature in productin.

But test by your own.

**Comment by SkylerLutz** [comment]
Will do -- thanks for that. What do you recommend for production workflows? Specifically with regard to exporting queue-related metrics

**Comment by GreenRover** [comment]
Think twice what queues are realy of interest and only scrape the metric of those queues using the filter option.

And think twice if you really need those metrics. Or haw you like to react if a metric is not ok.
May be you only need a stbilisation phase on integration level where you need to collect those metrics and not in production.

Otherwise add more cpu cores than solace advice for the choosen scaling tier.

**Comment by SkylerLutz** [comment]
Thanks for that. Related question -- is `Messages Queued (# msgs)` an exported metric? I don't see it on `QueueStats`

**Comment by GreenRover** [comment]
Yes QueueStats

https://github.com/solacecommunity/solace-prometheus-exporter/blob/master/solace_prometheus_exporter.go

There are 3 kinds of metrics:
*Details = very cpu intensive
*Stats = low to medium cpu intensive
  there are different meanings also solace internal if those metrics are problematic.
* = no problem at all

You habe to test it on its own. 
Please give feedback.
I only habe seen with QueueDetails
